Login
theman550/DAT257-K9 pull request #17
Opened 2020-09-17 20:45 UTC by karamaghi

Detta är min task , hoppas att fungeras som den ska va , jag har mergat med master och rättat alla konfliketer

2020-09-18 07:17 UTC, ITJohan requested changes
Riktigt nice! Har bara 3 smågrejer :grin:

2020-09-18 07:17 UTC, ITJohan commented on frontend/package.json
> +    "lint": "^0.7.0",
Är detta något vi behöver? Eslint är inbyggt i create-react-app

2020-09-18 07:17 UTC, ITJohan commented on frontend/src/components/Login.js
> +    `;
Lite konstig indentering här och på några andra ställen i styled components-definitionerna, vet att eslint inte tar upp det så man får göra det manuellt.

2020-09-18 07:17 UTC, ITJohan commented on frontend/src/components/Login.test.js
> +      <Router>
Router behövs endast om det är nånting i Login som använder react-router-dom.

2020-09-24 13:31 UTC, ITJohan commented
Är denna PR fortfarande aktuell eller ska jag ta bort den? @karamaghi

2020-09-24 15:08 UTC, karamaghi commented
> Är denna PR fortfarande aktuell eller ska jag ta bort den? @karamaghi 
Yes, kommer Pusha alla ändringar ikväll @ITJohan

2020-09-24 18:24 UTC, karamaghi commented
Jag har fixat alla konflikter i denna version

2020-09-25 07:37 UTC, ITJohan commented
Verkar som det det är några konflikter med App.js om du kollar längst den.

2020-09-25 07:50 UTC, karamaghi commented
> Verkar som det det är några konflikter med App.js om du kollar längst den.

Men jag har inte jobbat nåt med denna fil, den enda som jag lagt till i App.js är import Login from!

2020-09-28 12:26 UTC, ITJohan commented
Om du klickar på "files changed" längst upp på denna pull request så kommer du se vad lint klagar på. Om du fixar allt den klagar på så kommer testerna gå igenom och vi kan acceptera pull requesten.

2020-09-28 20:33 UTC, closed without merging