Add reusable UI components based on mockup design
theman550/DAT257-K9 pull request #24
Opened 2020-09-19 11:58 UTC by AndreasWJ

Behöver feedback! @ITJohan 
Se Typography.jsx. I den filen är idéen att jag ska definiera H3, H4 genom att extenda min H2.
Jag vet att man kan använda 'styled(H2)' vilket jag försökt med, men sedan vill jag att själva HTML taggen ska bli h3 respektive h4.
Finns en styled-components funktion 'withComponent(h3) eller withComponent(h4)', finns ett kommenterat exempel i koden.

Hursomhelst, skriver 'withComponent()' över den style man får från 'styled(H2)', vilket gör den oanvändbar.
Finns det någon sätt att lösa detta?

2020-09-21 12:21 UTC, ITJohan requested changes
La några kommentarer, är även problemet med kodformatering som vi måste lösa, se https://github.com/theman550/DAT257-K9/pull/22#issuecomment-696062893

2020-09-21 12:21 UTC, ITJohan commented on frontend/src/components/UI/index.jsx
> +}; */
Tycker inte vi ska ha utkommenterad kod i produktionskoden.

2020-09-21 12:21 UTC, ITJohan commented on frontend/src/components/UI/Typography.jsx
> +`.withComponent('h3'); */
Jag tvekar på att detta går eftersom h3 är en standardkomponent i JSX. Läste på https://styled-components.com/docs/api#withcomponent att funktionen även är deprecated och de rekommenderar att man använder https://styled-components.com/docs/api#as-polymorphic-prop istället. Jag tror inte det fungerar heller, men kan ju pröva. :relaxed:

2020-09-23 14:06 UTC, AndreasWJ commented
Fixat testerna, och tog bort gamla kommentarer.

Kollade på 'as' property:n innan, problemet med den är att det inte blir självklart vad taggen åstadkommer. Kommer se ut som:
```
<H2 as="h2">Header</H2>
```
Dumt skrivet av styled-components tycker jag.

2020-09-23 15:59 UTC, ITJohan approved these changes

2020-09-23 16:00 UTC, merged