Addtrip responsiv
theman550/DAT257-K9 pull request #49
Opened 2020-09-30 02:32 UTC by BasharDimaria

detta är Add trip responsiv , jag har gjort om nästan hela design för att passa desigen som Andreas gjort i Search trip , så jag har gjort precis lika med Description , jag har adderat Norification när vi får bad request och när resan adderade bra , detta är responsiv för mobil och ipad och dator , jag testat posta och notifciation och allt går smidigt . väntar på era svar. Tack

2020-09-30 07:57 UTC, ITJohan requested changes
Bra jobbat! Skrev några kommentarer och så hade det varit nice om du kunde baka in AddTrip.js i Trips.js så som jag gjorde med SearchTrips.js. Alltså
```
...
  onEscapeKeydown={() => setIsAddOpen(false)}
>
  <AddTrip closeAdd={() => setIsAddOpen(false)} />
</Modal>
<FloatingButtons
...
```

2020-09-30 07:57 UTC, ITJohan commented on frontend/src/App.js
> +
Varför är det mellanrum här?

2020-09-30 07:57 UTC, ITJohan commented on frontend/src/App.js
> +
Varför är det mellanrum här?

2020-09-30 07:57 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +  const [notification, setNotification] = useState(null);
notification ligger i App.js så denna kan tas bort.

2020-09-30 07:57 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +    };
Denna ligger i App.js, du måste skicka med den som en property: https://reactjs.org/docs/components-and-props.html

2020-09-30 07:57 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +    //--------------------------
Det här får gärna tas bort från produktionskoden.

2020-09-30 07:57 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +        <StyledButton onClick={closeAdd} type="button">Close</StyledButton>
I SearchTrip är dessa omvända och jag föreslår att vi kör samma här så det blir likt. Det är mest naturligt ur ett UX-perspektiv.

2020-09-30 16:50 UTC, BasharDimaria commented
in this last commit , jag har fixat notification kallase och mellan rum . det som gäller att lägga Addtrip i Trips.js , jag har lagt den men det dycker upp problem som jag kunde inte lösa fast jag jag satt med den nästan 3 timmar , det som hände är att när jag kallar Addtrip i Nav , allt går smidgt med size och responsive och notification , när jag kallar den i Trips, Trips kallar den mycket mindre Size och jag vet inte varför , och det blir inte i mitten , jag har kallat den precis på samma sätt i båda två men problemet ligger i Trips och jag kunde inte hitta den , så jag har bifogat de två lösningar i commiten för att ni få se skilnaden och jag hoppas att ni kan fixa den och hjälpa mig , det går mycket bra i Nav men inte inte i Trips. Tack

2020-10-01 09:49 UTC, ITJohan requested changes
Gav några kommentarer.

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/App.js
> +   const showNotification = (msg, color, seconds) => {
Dessa två kommentarer kan tas bort eftersom du nu använder funktionen, och då måste du även fixa indenteringen för att lint ska gå igenom.

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/App.js
> +          </Route>
Det här är gamla App.js, kolla hur nya ser ut och gör den lik + dina ändringar för AddTrip.

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +/* eslint-disable react/prop-types */
Lägg till PropTypes för denna komponent och ta bort denna kommentaren. Läs hur man gör på https://reactjs.org/docs/typechecking-with-proptypes.html

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/screens/Trips.js
> +import Addtrip from '../components/trips/AddTrip';
Är fint om du följer konventionerna för namn, ska alltså vara AddTrip, inte Addtrip.

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/screens/Trips.js
> +          <Addtrip closeAdd={() => setIsAddOpen(false)} showNotification={() => {}} />
Samma sak med namnet här, AddTrip. Vad är meningen med showNotification egentligen? Känns som du bara fuskat här. showNotification måste "prop drillas" från App, alltså gå från App -> Trips -> AddTrip.

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +    //--------------------------
Som jag sa så vill vi inte ha detta i produktionskoden.

2020-10-01 09:49 UTC, ITJohan commented on frontend/src/components/trips/AddTrip.js
> +    <div className="SearchGui">
Problemet med att designen ballar ur är att du har en extra div här. Så formulärets bred på 80% är utifrån denna.

2020-10-01 18:09 UTC, ITJohan approved these changes
Fixade de kvarstående problemen så vi kan merga.

2020-10-01 18:09 UTC, merged