Register user
theman550/DAT257-K9 pull request #50
Opened 2020-09-30 08:17 UTC by nooraluay

2020-09-30 13:47 UTC, AndreasWJ requested changes
Kollar igenom koden lite för feedback. Men kan du göra mig en tjänst och dra ner dom senaste ändringarna från master och göra en ytterligare commit? Det är svårt för mig annars att ge rätt feedback 😄. Skriv detta:
```
git checkout master
git pull origin master

git checkout register-user
git merge origin/master
```

Förhoppningsvis slipper du konflikter.

2020-09-30 14:11 UTC, nooraluay commented
Sorry , jag glömde göra detta. Jag pushade koden nu

2020-09-30 22:26 UTC, AndreasWJ requested changes
Inga problem, glömmer ofta att dra ner från master själv 🙃. Såg att du lyckats få till det fint responsivt! Har lite feedback som design-ansvarig om tidigare commits som gäller din komponent.

**UI Komponenter**
Rekommenderar starkt att du använder dig av de UI komponenter som redan finns, dessa finns i 'src/components/UI'. I Form.js kan du byta ut din h1, dina text fält, och din submit till H2, FieldFactory, och Primary Button respektive. Exempelvis:
```
import { H2 } from 'components/UI/Typography';
import FieldFactory from 'components/UI/Field';
```

Om du vill göra lokala förändringar, exempelvis ändra färg på din importerade H2, eller skapa ett textfält:
```
const myH2 = styled(H2)`
...
`;
const myInputField = FieldFactory(styled.input``);
```

**Design variabler**
Enligt design mockupen finns ett antal färger(färgschema) samt bestämda mellanrum i form av margin och padding. Dessa kan du se under 'src/themes/base.js'. För att nå, exempelvis, den lila(primära) färgen skriver du detta inuti din CSS kod:
```
const InputSub = styled.input`
    width: 60%;
    padding: 12px 20px;
    margin: 8px 0;
    background: ${(props) => props.theme.colors.primary};
    border: none;
    border-radius: 15px;
    padding: 10px;
    color: white;
    font-family: "Noto Sans", sans-serif;
    font-size: 14px;
    cursor: pointer;
    `;
```
Som sagt, kolla 'src/themes/base.js' och använd dessa variabler så mycket du kan!

**Centrera formulär**
Såg i Form.js att du försökt centrera formuläret(variabeln F) med följande kod:
```
    position: absolute;
    top: 56%;
    left: 50%;
    -webkit-transform: translate(-50%,-50%);
    -ms-transform: translate(-50%,-50%);
    transform: translate(-50%,-50%);
```
Problemet att centrera på detta sätt är att elementet inte är ett del av "dokument flödet", vilket gör det svårt för dig att lägga till ytterligare element i framtiden. Rekommenderar att du lägger till en så kallad "wrapper div" runt ditt formulär som centrerar formuläret. Exempelvis:
```
<Wrapper>
    <F>...</F>
</Wrapper>
```
```
const Wrapper = styled.div`
display: flex;
justify-content: center;
align-items: center;
`;
```
Koden ovan kanske inte fungerar perfekt men försök med lite olika sätt att centrera.

**Ta bort username?**
Vet inte om vi ska använda username fältet. Men vi kan ha kvar det för tillfället.

Om du gör dessa ändringar kommer du märka att det inte blir så mycket arbete. Mycket finns redan definierat i 'src/components/UI', mycket går att återanvända med andra ord. Om det är några frågor, säg till!

2020-10-01 10:38 UTC, nooraluay commented
Hej, Jag ändrade allt som du sagt.Nu väntar jag på ett feedback från er.

2020-10-01 18:22 UTC, AndreasWJ requested changes
Bra ändringar!

Har lite mer feedback dock, förlåt för att jag är petig 😀.

**Formuläret och sidoflöde**
Såg att du lade till en wrapper runt din komponent vilket är riktigt bra praxis! Det enda du glömt göra är att ta bort 'position: absolute' från din F, form elementet. Som jag nämnde förut, 'position: absolute' tar bort elementet ur sidan flöde(vilket man endast vill ha i särskilda situationer). Om du tar bort:
```
position: absolute;
    top: 56%;
    left: 50%;
    transform: translate(-50%, -50%);
```
Kommer din form hamna i wrappern du gjorde, vilket är bra! Sedan kan du fokusera på att centrera, finns ett antal tekniker för att göra det. Annars kan du låta formuläret ligga längre upp på sidan, det är enklare att åstadkomma.

**Ta bort okända typsnitt**
Rekommenderar att du tar bort okända(för vår design) typsnitt. Detta är för att våran app ska kännas mer som en app och inte flera sidor ihopklistrade. Här rekommenderar jag att ändra:
```
const InputText = FieldFactory(styled.input`
    font-family: Arial, Helvetica, sans-serif;
    `);
```

```
const InputPassword = FieldFactory(styled.input`
    font-family: Arial, Helvetica, sans-serif;
    `);
```

**Primary button**
Såg att din knapp är exakt som den i 'components/UI/PrimaryButton', rekommenderar starkt att du byter till den så slipper du själv specificera egen CSS också. Jag tänker på din submit button:
```
const Button = styled.button`
    position: relative;
    margin: 15px 0 5px 0;
    margin-top: 0px;
    margin-left:80px;
    left: 5%; 
    transform: translateX(-50%);
    background: ${(props) => props.theme.colors.primary};
    border: none;
    border-radius: 5px;
    padding: 10px;
    color: ${(props) => props.theme.colors.alternateFill};
    width: 60%;
    font-family: "Noto Sans", sans-serif;
    font-size: 14px;
    cursor: pointer;
        `;
```
Hela den kan bytas ut med:
```
const Button = styled(PrimaryButton)`
    padding: 10px;
    width: 60%;
    cursor: pointer;
        `;
```
Förutsatt att du importerat PrimaryButton.

2020-10-02 06:32 UTC, nooraluay commented
Hej,

Jag hoppas nu att koden uppfyller dina krav :)
Gällande wrapper så förstådd jag inte vad du menade med att centrera den, när jag tog bort all parametrarna du nämnde så så var den fortfarande centrerad.

2020-10-02 08:38 UTC, AndreasWJ commented
> Hej,
> 
> Jag hoppas nu att koden uppfyller dina krav :)
> Gällande wrapper så förstådd jag inte vad du menade med att centrera den, när jag tog bort all parametrarna du nämnde så så var den fortfarande centrerad.

Tror något blev fel med commiten. Ser inga skillnader.
Du commitade bara "Merge branch 'master' into register-user" 😳

2020-10-02 08:47 UTC, nooraluay commented
Hej;
Jag skickade detta nu.
________________________________
Från: Andreas W Johansson <notifications@github.com>
Skickat: den 2 oktober 2020 10:38
Till: theman550/DAT257-K9 <DAT257-K9@noreply.github.com>
Kopia: Noora Al-Sadawi <alsadawi@student.chalmers.se>; Author <author@noreply.github.com>
Ämne: Re: [theman550/DAT257-K9] Register user (#50)


Hej,

Jag hoppas nu att koden uppfyller dina krav :)
Gällande wrapper så förstådd jag inte vad du menade med att centrera den, när jag tog bort all parametrarna du nämnde så så var den fortfarande centrerad.

Tror något blev fel med commiten. Ser inga skillnader.
Du commitade bara "Merge branch 'master' into register-user" 😳

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/theman550/DAT257-K9/pull/50#issuecomment-702602590>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AQ2O2SUPXD62E47ZSORCLNTSIWGQZANCNFSM4R6YZVTA>.

2020-10-02 08:57 UTC, AndreasWJ commented
Byt ut "User Account" till annan text så mergar vi!

2020-10-02 09:54 UTC, AndreasWJ requested changes
Just det, ta bort username från register fälten. Vi behöver det inte på backend.
Byt namn på "User Account" till något annat som Johan nämnde.

2020-10-02 16:10 UTC, AndreasWJ approved these changes
Riktigt bra jobbat! Mergar!

2020-10-02 16:10 UTC, merged