About us
theman550/DAT257-K9 pull request #63
Opened 2020-10-07 07:06 UTC by nooraluay

2020-10-08 08:50 UTC, AndreasWJ commented
Designade om en carpool vektor och la till istället för bilden, hoppas det inte gör något!
La även till About komponenten vid router root.

2020-10-08 08:52 UTC, AndreasWJ requested changes
Gillar det du skrivit hittills!
Funderar på om man kan få in lite mer om appen. Ser ganska tomt ut. Hade varit nice om du kunde utöka med lite innehåll horisontellt också. Typ kort beskrivet dess funktioner. Kanske även instruktioner för hur man använder dom.

@ITJohan har du några idéer om vad man kan lägga till?

2020-10-08 08:52 UTC, AndreasWJ commented on frontend/src/components/About.js
> +`;
Rekommenderar att du tar bort font-sizes från dessa. Det är okej att öka storleken på text utifrån det som finns definierat i Typography.jsx men du har redan gjort det för din H1. Om man ökar storleken på all text så blir det en ny standard och skärmen passar inte in bland våra andra komponenter.

`font-family: Kufam, sans-serif;` behövs inte eftersom Typography.jsx och dess header redan har en sådan property.

2020-10-08 17:11 UTC, nooraluay commented
Hej , 
Förlåt mig för att jag svara er försent, mycket upptaget med mina tentor. Jag kan fixa paragrafen så den ska vara centrerad i mitten.
Andreas, jag kan ta bort font-size& font-family. 
behöver jag lägga till något mer eller det räcker?

2020-10-08 18:14 UTC, nooraluay commented
Jag ska försöka fixa allt under helgen, om jag behöver jag ska kontakta er

2020-10-14 07:21 UTC, ITJohan requested changes
![Screenshot from 2020-10-14 09-15-38](https://user-images.githubusercontent.com/29819674/95956015-f9934f80-0dfd-11eb-8eae-8b71cf82176f.png)
Jag tycker bilden blir lite stor här, personligen tycker jag bilden på bilen var bättre. Vad tycker ni @nooraluay @AndreasWJ ? 

![Screenshot from 2020-10-14 09-15-54](https://user-images.githubusercontent.com/29819674/95956258-54c54200-0dfe-11eb-9a4c-b19af9b92c6b.png)
Här blir det ganska fult tycker jag, det borde vara margin på sidorna så att texten inte går ända ut. Bilden kanske kan göras så att den täcker hela bredden också?

Annars bra jobbat!

2020-10-14 07:21 UTC, ITJohan commented on frontend/src/components/About.js
> +    <div className="">
Varför har denna en tom className?

2020-10-16 07:16 UTC, closed without merging