Auto complete
theman550/DAT257-K9 pull request #66
Opened 2020-10-08 02:28 UTC by BasharDimaria

jag har klarat den som första inblick , kolla på den om det är allt okey , jag ska implemnterea fältena till Sök form  också . 
Tack

2020-10-08 02:35 UTC, BasharDimaria commented
jag har gjort npm run lint och allt funkar , jag ve inte varför är det inte okey med github checking

2020-10-08 06:26 UTC, ITJohan commented
Verkar vara nån konflikt med package-lock.json, kolla https://stackoverflow.com/questions/47074219/npm-err-unexpected-token-in-json-at-position-12842

2020-10-08 07:57 UTC, AndreasWJ commented
@BasharDimaria Pröva att köra en `npm install` i frontend på nytt. Fungerade för mig när jag fick samma problem

2020-10-08 14:42 UTC, BasharDimaria commented
jag har fixat json och lint , allt  är okey , förutom validation i Autoselect , jag vet inte hur kan jag fixa det , om nogån kan hjälpa  mig i detta .

2020-10-08 19:02 UTC, BasharDimaria commented
jag har fixat allt .  :) , om nogåt behövs att ändra , kommenterea bara

2020-10-09 00:17 UTC, AndreasWJ commented
Har börjat kolla igenom koden. Designmässigt, finns det någon lösning utan Material komponenter? Det är lugnt om du kör någon modul för själva typeahead funktionaliteten, men själva textfälten tycker jag inte passar in med resten av formulären

2020-10-10 02:29 UTC, BasharDimaria commented
jag har fixat det bästa design jag kan för detta , Andreas jag väntar på din svar om vad du tycker , jag troro inte att jag kan ändra mycket på componenten än det som det är just nu , annan sak , jag föstökte implemtera detta i den Sökcomponeten , men det verkar att du inte använder fromik längre , det är en problem för att detta kan implneteras bara på Field pga att det har component props som man kan andra kompntet , jag är rädd att ändra din till Formik och allt rivas ner :) så jag vill först se vad du tycker om design och hur vi kan lösa Filed problem .

2020-10-10 16:07 UTC, AndreasWJ requested changes
Har försökt lite att få till rätt styling på Autocomplete fältet, dock vägrar Material att låta en göra nödvändiga ändringar. Jag tycker vi jobbar om komponenten i bakgrund till vår nya "Definition of done", regeln om att allt måste följa mockupen(dess riktlinjer iallafall).

Förstår att du lagt ner mycket arbete i komponenten som finns nu. Ser det i koden. Men tror det samtidigt är intressant att skriva en själv. Har gjort det innan själv, och det är inte så svårt som man tror när man väl kommer igång.

Denna sprint som börjar på måndag har du ju en ganska enkel story, att länka mellan login och register. Men vad sägs om att implementera en egen Typeahead komponent? Det är en utmaning, men tror du kan klara det utan problem! Jag kan hjälpa till självklart, men finns bra tutorials som går igenom hela komponenten. Främst https://medium.com/@svsh227/create-your-own-type-ahead-dropdown-in-react-599c96bebfa
Det räcker egentligen att ta koden i artikeln, läsa igenom den flera gånger och se till att du förstår den. Om du skulle behöva hjälp med design så säg till!

Kan även göra den själv, men har en jäkla massa stories nästa sprint... Vad tycker du?

2020-10-13 16:28 UTC, closed without merging