Login
theman550/DAT257-K9 pull request #72
Opened 2020-10-08 22:24 UTC by karamaghi

jag har redesignat Login enligt Andreas komponent och allt gick bra .

2020-10-09 00:21 UTC, AndreasWJ commented
Tjenare! Såg att du glömt att hämta senaste ändringarna från master. Kan du göra det?
Svårt för mig annars att jämföra design, och veta att koden kommer fungera som förväntat.

2020-10-09 06:37 UTC, ITJohan commented
Kan flika in med följande:

- Ikonen är inte i center (margin 40%?)
- Knappen är inte i center (margin-left 1rem?)

2020-10-09 10:44 UTC, karamaghi commented
> Kan flika in med följande:
> 
> * Ikonen är inte i center (margin 40%?)
> * Knappen är inte i center (margin-left 1rem?)

Jag fixade ikonen, och submit knappen så de hamnar i mitten

2020-10-09 10:45 UTC, karamaghi commented
> Tjenare! Såg att du glömt att hämta senaste ändringarna från master. Kan du göra det?
> Svårt för mig annars att jämföra design, och veta att koden kommer fungera som förväntat.

Står det att den är redan uppdaterad, iaf jag har uppdaterat igen.

2020-10-10 15:51 UTC, AndreasWJ requested changes
Förlåt för sen respons Karam! Hade inte möjligheten att gå igenom det igår efter mötet.

I Account.js använder du:
```
  width: 100vw;
  height: 100vh;
```
Rekommenderar att du tar bort dessa. Eftersom enheter som vw och vh måste användas försiktigt då det inte tar hänsyn till andra komponenter, såsom vår navbar. Resultatet blir horisontell scrolling vilket inte ser bra ut. Dessa kan du ta bort helt, blir ingen skillnad.

Kan du även lägga till raden nedan i Account.js, i Container klassen?
```
padding: ${(props) => props.theme.padding.section};
```
På så sätt blir det lite ledigt utrymme mellan navbar och ditt formulär.

Inte mycket annat än så. Responsiv. Bra layout på formuläret! Gillar speciellt det du gjort med ikonen!

2020-10-10 15:51 UTC, AndreasWJ commented on frontend/src/components/Login.js
> +  margin: 30% auto;
Ta bort denna rad.

Förstår att du försöker centrera formuläret men detta är inte en bra lösning. Margin centrering är utdaterat, rekommenderar istället att köra endast flexbox. Dessutom skalas formuläret konstigt med denna margin.

Centrering är inget krav. Du kan försöka att få till det med flexbox, men är enklast att undvika det för tillfället.

2020-10-10 15:51 UTC, AndreasWJ commented on frontend/src/components/Login.js
> +  margin-top: ${(props) => props.theme.spacing.subsection};
Kan du flytta dessa rader in till StyledPrimaryButton där under? Och sedan ta bort Button?
Är lättare att läsa koden då 😃

2020-10-11 15:13 UTC, karamaghi commented
> Förlåt för sen respons Karam! Hade inte möjligheten att gå igenom det igår efter mötet.
> 
> I Account.js använder du:
> 
> ```
>   width: 100vw;
>   height: 100vh;
> ```
> 
> Rekommenderar att du tar bort dessa. Eftersom enheter som vw och vh måste användas försiktigt då det inte tar hänsyn till andra komponenter, såsom vår navbar. Resultatet blir horisontell scrolling vilket inte ser bra ut. Dessa kan du ta bort helt, blir ingen skillnad.
> 
> Kan du även lägga till raden nedan i Account.js, i Container klassen?
> 
> ```
> padding: ${(props) => props.theme.padding.section};
> ```
> 
> På så sätt blir det lite ledigt utrymme mellan navbar och ditt formulär.
> 
> Inte mycket annat än så. Responsiv. Bra layout på formuläret! Gillar speciellt det du gjort med ikonen!

@AndreasWJ  Jag tror att vi måste snacka med @ITJohan  innan vi tar bort (  width: 100vw; height: 100vh;), då det är han som la till det.

2020-10-11 17:27 UTC, AndreasWJ commented
> > Förlåt för sen respons Karam! Hade inte möjligheten att gå igenom det igår efter mötet.
> > I Account.js använder du:
> > ```
> >   width: 100vw;
> >   height: 100vh;
> > ```
> > 
> > 
> > Rekommenderar att du tar bort dessa. Eftersom enheter som vw och vh måste användas försiktigt då det inte tar hänsyn till andra komponenter, såsom vår navbar. Resultatet blir horisontell scrolling vilket inte ser bra ut. Dessa kan du ta bort helt, blir ingen skillnad.
> > Kan du även lägga till raden nedan i Account.js, i Container klassen?
> > ```
> > padding: ${(props) => props.theme.padding.section};
> > ```
> > 
> > 
> > På så sätt blir det lite ledigt utrymme mellan navbar och ditt formulär.
> > Inte mycket annat än så. Responsiv. Bra layout på formuläret! Gillar speciellt det du gjort med ikonen!
> 
> @AndreasWJ Jag tror att vi måste snacka med @ITJohan innan vi tar bort ( width: 100vw; height: 100vh;), då det är han som la till det.

Ah, det kan vi göra. Bra att du sa det 👍

2020-10-12 07:17 UTC, ITJohan commented
@karamaghi Bara att ändra det du behöver, inte jag som äger koden. :grin:

2020-10-14 13:55 UTC, karamaghi commented
Feedback from @ITJohan  @AndreasWJ  about last login has been fixed. in addition to 
1.Navigation between the new login and register has been applied to login page via en link. 
2. Register had so many bugs regarding the input fields, email type was text so it has been changed to email, password and confirm password didn't work properly, it was just design without any functionality, all has been fixed. 
3.Another edit has been added in case password is matched and submit is clicked , the user will be redirected to login page and will get notification that registered has been successfully made, if it is not matched password, the user will get notification about that and should rewrite their info.

2020-10-14 14:35 UTC, AndreasWJ approved these changes
Kollat igenom koden och testat den. Bra design ändringar, och riktigt bra initiativ att förbättra register! Fortsätt med det!

La till två commits själv som ändrar små design detaljer, och ändrade några namn på variabler så vi håller oss konsekventa.
@karamaghi kolla igenom dessa commits, om det är något du undrar över eller nåt jag gjort fel, så skicka ett meddelande!

2020-10-14 14:36 UTC, merged