Separate navbars
theman550/DAT257-K9 pull request #75
Opened 2020-10-12 13:29 UTC by ITJohan

Navbaren visar endast login när man är utloggad, och trips, account och logout när man är inloggad. Fixade också så att inloggad state ändras när man registrerar eller loggar in. Klickar man logout så loggas man ut.

Logout verkar fungera men ger `GET http://spilg.xyz/api/login/ net::ERR_ABORTED 500 (Internal Server Error)`. Man kan logga in utan att skriva in något men det är ett problem med Login.js och behandlas inte i denna PR.

2020-10-13 12:03 UTC, AndreasWJ commented
Tjenare!
Har börjat kolla igenom koden. Ser bra ut för övrigt. Men tänkte om det fanns ett sätt att hämta information från sessionen, jag tänker framförallt på userID. Med userID kan vi sedan /api/users/:userID/ och hämta information såsom namn. Vilket kan användas för att få upp en "profilbild" i navbaren med användaren initialer.

Ska se om jag hittar något. Med JWTs kan man ju läsa, så bör ju finnas nånting med sessioner också.

2020-10-13 12:13 UTC, ITJohan commented
> Tjenare!
> Har börjat kolla igenom koden. Ser bra ut för övrigt. Men tänkte om det fanns ett sätt att hämta information från sessionen, jag tänker framförallt på userID. Med userID kan vi sedan /api/users/:userID/ och hämta information såsom namn. Vilket kan användas för att få upp en "profilbild" i navbaren med användaren initialer.
> 
> Ska se om jag hittar något. Med JWTs kan man ju läsa, så bör ju finnas nånting med sessioner också.

Japp håller med, har haft svårt att jobba på grund av alla backend-problem och oklarheter med cookies. Därför blev det denna version. :) Det verkar som att vi kommer få tillgång till en token/sessionID som vi kan använda för att identifiera oss till backend. Då kan jag bara byta allt till token och setToken eller liknande för samma funktionalitet.

2020-10-14 08:24 UTC, ITJohan commented
@AndreasWJ Fixade så att att vi har en "global" loggedInUser nu med token och email enligt det nya backend-systemet. Ge gärna feedback på vad du tror om det. :)

2020-10-14 14:51 UTC, AndreasWJ requested changes
Kollat igenom koden, är lite förvirrad än av autentiseringsflödet, men tror jag börjar förstå vad som händer 😄.

Det enda som jag inte hänger med på är; varför skickas loggedInUser och setLoggedInUser med till Form.js(register sidan)? Först tänkte vi ju att register endast skulle registrera och inte "automatiskt logga in", men håller med att det är dåligt från ett UX perspektiv.

Räcker det att skicka med setLoggedInUser till Form.js? På så sätt kan den definieras vid registrering. Jag tänker loggedInUser.token och loggedInUser.email inte behövs vid registrerings fetch då registreringsprocessen inte ska autentiseras

2020-10-14 15:49 UTC, ITJohan commented
Det har du helt rätt i, vet inte varför jag skicka med det i Form :sweat_smile: Slänger upp en fix!

2020-10-14 16:11 UTC, AndreasWJ commented
> Det har du helt rätt i, vet inte varför jag skicka med det i Form 😅 Slänger upp en fix!

Tagga mig här när den är uppe! Väntar med att göra ändringar i min branch, så jag slipper konflikter

2020-10-14 17:07 UTC, ITJohan commented
@AndreasWJ Så nu ska det mesta med logged in state och requests vara fixat. Löste några problem som fanns i den andra PRn som mergades också.

2020-10-14 17:51 UTC, AndreasWJ approved these changes
Lade till en liten commit efter din, det var bara två props som stod oanvända.

Bra jobbat! Mergar!

2020-10-14 17:51 UTC, merged