fix lint
theman550/DAT257-K9 pull request #77
Opened 2020-10-13 12:33 UTC by nooraluay

2020-10-14 07:38 UTC, ITJohan requested changes
Jag hade velat se att landing page hade hamnat i en egen komponent och inte ligga i App.js, kanske LandingPage.js? App.js är mest till för att hantera routingen och gemensam state.

![Screenshot from 2020-10-14 09-24-53](https://user-images.githubusercontent.com/29819674/95957054-7b37ad00-0dff-11eb-8f31-8b22626be0eb.png)
Jag snacka om att vi skulle ha en stor logotyp längst upp men du kanske missa det. Vad tycker ni om det @nooraluay @AndreasWJ ? Jag skulle också vilja se att underrubriken "We ignite opportunity..." endast är på en rad här och kanske lite mindre då.

![Screenshot from 2020-10-14 09-27-10](https://user-images.githubusercontent.com/29819674/95957328-dec1da80-0dff-11eb-88e2-ada7d2ea1835.png)
I mobilversionen tycker jag underrubriken fortfarande borde vara på en rad medans paragrafen borde ha en margin och inte gå ut ända till sidorna. Vad tycker ni? Borde även ha logotypen här längst upp.

Sen glöm inte att ta bort det svarta "Welcome to Share-a-ride" längst upp till vänster.

Edit: Ta gärna lite inspiration från https://blog.hubspot.com/marketing/fantastic-landing-page-examples :)

2020-10-14 07:38 UTC, ITJohan commented on frontend/src/App.js
> -import ErrorBoundary from './components/ErrorBoundary';
Varför har du tagit bort ErrorBoundary?

2020-10-14 07:38 UTC, ITJohan commented on frontend/src/App.js
> +                <div className="">
Varför har du en tom className här?

2020-10-15 05:49 UTC, ITJohan commented
Det verkar som att du inte mergat med master korrekt av vad jag kan se på commit-historiken. Som jag skrivit flera gånger tidigare är det viktigt att du laddar ned senaste mastern och mergar denna med din branch.
```
git checkout master
git pull
git checkout home-page
git merge master
```
Har du GitHub desktop, GitKraken eller liknande? Jag tror du måste gå tillbaks till en tidigare commit och lägga på dina ändringar där ifrån, annars kommer git-historiken bli helt kaos.

2020-10-15 07:08 UTC, nooraluay commented
> Det verkar som att du inte mergat med master korrekt av vad jag kan se på commit-historiken. Som jag skrivit flera gånger tidigare är det viktigt att du laddar ned senaste mastern och mergar denna med din branch.
> 
> ```
> git checkout master
> git pull
> git checkout home-page
> git merge master
> ```
> 
> Har du GitHub desktop, GitKraken eller liknande? Jag tror du måste gå tillbaks till en tidigare commit och lägga på dina ändringar där ifrån, annars kommer git-historiken bli helt kaos.

Jag gjorde det och fick konflikt, när allt var fixat så gick det att pusha.
För tillfället är det bara bash jag använder, är det enkelt att fixa git historiken via kommandon?

2020-10-16 07:16 UTC, closed without merging