Thezzern patch 1
theman550/DAT257-K9 pull request #80
Opened 2020-10-13 16:50 UTC by thezzern

Token passing support för validering av logout och tillägning av resor. Get trips kräver ingen validering längre alls. Login ger tillbaka en mail och ett token, för resurser som kräver validering måste emailen och token som fås vid inloggning sparas. De ska sen sättas som post parameterar. Måste sättas till POST "loggedInEmail" och "token" exakt som det står inom "". Validering för users lägger jag till om detta funkar för servern också. (kan bara testa lokalt utan att mergea till servern).

2020-10-13 18:52 UTC, ITJohan commented on backend/html/api.php
> +	header('Access-Control-Allow-Origin: localhost:3000'); // <- Ersätt med null för att använda lokalt
Denna måste vara http://locahost:3000

2020-10-13 19:02 UTC, thezzern commented on backend/html/api.php
> +	header('Access-Control-Allow-Origin: localhost:3000'); // <- Ersätt med null för att använda lokalt
Ja precis, tänkte inte på att den inte var uppdaterad, har ändrat det nu 👍

2020-10-14 06:45 UTC, theman550 requested changes
Två små anmärkningar som jag vill att du ska kika på, annars ser det bra ut! Föreslår rejäl refraktorisering där vi bryter upp api.php som nästa steg.

2020-10-14 06:45 UTC, theman550 commented on backend/html/api/login/index.php
> +		if(isset($data->loggedInEmail) && isset($data->token))
$data är undefined här va? 🤔

2020-10-14 06:45 UTC, theman550 commented on backend/html/api/login/index.php
> +		if(isset($data->loggedInEmail) && isset($data->token))
$data är undefined här tror jag va? 🤔

2020-10-14 06:45 UTC, theman550 commented on backend/html/api/trips/index.php
>  			/*if(isset($data->startLocation) && isset($data->destination) && isset($data->price) && isset($data->startTime) && isset($data->seatsAvailable) && isset($data->description) && isset($data->userID)
Kan inte kommentera där nere, men felkoden som kommer om inte verify funkar (rad 43) kanske skulle vara annorlunda än det man får när det är fel på datan (validateTrip)? Ändra till 401 eller nåt bara så blir det tydligare vart det felar, om det felar :)

2020-10-14 08:38 UTC, thezzern commented
Sådär, nu ska de stämma också :)

2020-10-14 08:39 UTC, theman550 approved these changes

2020-10-14 08:40 UTC, merged