Implement an account component displaying user data and user trips with option to cancel
theman550/DAT257-K9 pull request #81
Opened 2020-10-14 22:30 UTC by AndreasWJ

Account sidans förfrågningar fungerar inte för tillfället, då de kräver resurser som /api/bookings och /api/users, vilket inte vara implementerade än. Kräver också en id parameter, /api/users/1 exempelvis, vilket jag antar redan är implementerat. Man kan dock testa koden genom mockups som jag kommenterat ut.

Många ändringar för en PR kanske, men här är det:
- Bytte namn och route på login skärmen, från '/account' till '/login'.
- Lade till min account komponent vid '/account' istället.
- Lade till en mapp för modeller, med andra ord, prop type definitioner. Just nu trips, bookings, user payload(email och token), och theme shape. Bra att återanvända i resten av koden. De flesta går även att förlänga genom spread operatorn, se CancelCard.jsx för exempel. Dessa erbjuder även toTripEntity och toBookingEntity respektive. Tanken med dessa "map" funktioner är att de ska ta hand om skillnader mellan backend och frontend. Säg att backend har ett annorlunda namn på en property eller liknande.
- Refaktoriserade hela kort komponenten. Jag hamnade i en situation där det skulle vara ett och samma kort fast olika "controls". Gjorde därmed ett "baskort", Card.jsx, och sedan CancelCard.jsx och BookCard.jsx. Dessa skickar en prop vid namn controlFactory som genererar unika controls utifrån en trip. Exempelvis, går det nu att avboka med hjälp av trip id!
- Bytte ut appens scrollbar till en som passar designen.
- Lade till en mapp med mocks, just nu med trips och bookings.
- Lade till två färger som är specifika för situationer; success och error. Tänker att dessa framförallt ska användas i sammanhang med notifikationer, så gick igenom alla komponenter och ändrade color: 'red' osv till dessa. Det är viktigt att vara konsekvent. För att få tillgång till theme variabler så måste ni exportera era komponenter med `withTheme(KomponentNamn);`. På så sätt får ni tillgång till en prop theme. Och använder den som vanligt mer eller mindre; `theme.colors.success` exempelvis.

2020-10-15 06:49 UTC, ITJohan requested changes
Woooow, riktigt mastig PR! :star_struck: Ser sjukt bra ut, testade med mocksen och det fungera perfekt. Blev lite errors o grejer om man loggar ut när man är på account-sidan, går det att lägga till en check att man är inloggad som jag gjorde på rad 66 i App.js för /account? Är ju en ganska ful lösning men kanske funkar under rådande omständigheter :grin: 

Riktigt bra jobbat iaf, känns som vi börjar ro detta i land nu!

2020-10-15 06:49 UTC, ITJohan commented on frontend/src/components/Trip/Card/BookCard.jsx
> +        return showNotification(error.message, theme.colors.error, 5);
Varför returneras showNotification? Är det pga lint? Det kommer returnera undefined som jag förstår det.

2020-10-15 10:43 UTC, AndreasWJ commented on frontend/src/components/Trip/Card/BookCard.jsx
> +        return showNotification(error.message, theme.colors.error, 5);
I de fallet är det inte lint. Efter den catch har jag:
```
    console.log('Successful booking!');
    // Decrease card's seats with numberOfSeats
    return setSeats(seats - numberOfSeats);
```
Jag vill endast att setSeats ska kallas i det fall då inget fel kastas, därmed returnerar jag tidigt i varje catch. Finns det något bättre sätt att skriva det tro? Håller med om att många return statements gör koden svårare att läsa, speciellt när return värdet inte spelar roll då jag kallar funktionen med `submitBooking(...)`;

2020-10-15 10:51 UTC, ITJohan commented on frontend/src/components/Trip/Card/BookCard.jsx
> +        return showNotification(error.message, theme.colors.error, 5);
Ah ok då förstår då! Var mest nyfiken på tänktegången här. :grin:

2020-10-15 13:10 UTC, ITJohan approved these changes

2020-10-15 13:10 UTC, ITJohan commented
Accepterar så får du merga när du vill @AndreasWJ

2020-10-16 07:21 UTC, ITJohan commented
Mergar nu så jag kan merga till min branch :)

2020-10-16 07:21 UTC, merged